Update botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 clear
-[[ $(awk -F" " '{print $2}' /usr/lib/licence) != "@KIRITO_SSH" ]] && exit 0
+[[ $(awk -F" " '{print $2}' /usr/lib/licence) != "@NET_SATOSHI" ]] && exit 0
 fun_bar() {
     comando[0]="$1"
     comando[1]="$2"
@@ -33,19 +33,19 @@ fun_botOnOff() {
     [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) = '0' ]] && {
         clear
         echo -e "\E[44;1;37m             INSTALADOR BOT VPS MANAGER                \E[0m\n"
-        echo -ne "\033[1;32mINFORME SEU TOKEN:\033[1;37m "
+        echo -ne "\033[1;32mCONFIRME SU TOKEN:\033[1;37m "
         read tokenbot
         echo ""
-        echo -ne "\033[1;32mINFORME SEU ID:\033[1;37m "
+        echo -ne "\033[1;32mCONFIRME SU ID:\033[1;37m "
         read iduser
         clear
         echo -e "\033[1;32mINICIANDO BOT VPS MANAGER \033[0m\n"
         fun_bot1() {
         	[[ "$(grep -wc '16' /etc/issue.net)" != '0' ]] && {
-        		wget -qO- https://raw.githubusercontent.com/NT-GIT-HUB/VPS-MANAGER-1.0/main/Install/ShellBot.sh > /etc/VPSManager/ShellBot.sh
+        		wget -qO- https://raw.githubusercontent.com/Satoshi-v/script-premiun/master/Install/ShellBot.sh > /etc/VPSManager/ShellBot.sh
         	}
             [[ ! -e "/etc/VPSManager/ShellBot.sh" ]] && {
-				wget -qO- https://raw.githubusercontent.com/NT-GIT-HUB/VPS-MANAGER-1.0/main/Install/ShellBot.sh >/etc/VPSManager/ShellBot.sh
+				wget -qO- https://raw.githubusercontent.com/Satoshi-v/script-premiun/master/Install/ShellBot.sh >/etc/VPSManager/ShellBot.sh
 			}
             cd /etc/VPSManager
             screen -dmS bot_plus ./bot $tokenbot $iduser >/dev/null 2>&1
@@ -62,7 +62,7 @@ fun_botOnOff() {
             cd $HOME
         }
         fun_bar 'fun_bot1'
-        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT VPS MANAGER ATIVADO !\033[0m" || echo -e "\n\033[1;31m ERRO! REANALISE SUAS INFORMACOES\033[0m"
+        [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT VPS MANAGER ACTIVADO !\033[0m" || echo -e "\n\033[1;31m ERROR! REANALISA SUS DATOS\033[0m"
         sleep 2
         menu
     } || {
@@ -86,13 +86,13 @@ fun_botOnOff() {
 
 fun_instbot() {
     echo -e "\E[44;1;37m             INSTALADOR BOT VPS MANAGER                \E[0m\n"
-    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCAO \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mPELO SEU TELEGRAM ACESSE OS SEGUINTES BOT\033[1;37m:\033[0m"
-    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCRIE O SEU BOT \033[1;31mOPCAO: \033[1;37m/newbot\033[0m"
-    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@@useridinfobot \033[1;33mE PEGUE SEU ID \033[1;31mOPCAO: \033[1;37m/id\033[0m"
+    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mDESDE SU TELEGRAM ACESSA LOS SEGUINTES BOT\033[1;37m:\033[0m"
+    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREE SU BOT \033[1;31mOPCION: \033[1;37m/newbot\033[0m"
+    echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@@useridinfobot \033[1;33mE PEGUE SU ID \033[1;31mOPCION: \033[1;37m/id\033[0m"
     echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
     echo ""
-    read -p "DESEJA CONTINUAR ? [s/n]: " -e -i s resposta
+    read -p "DESEA CONTINUAR ? [s/n]: " -e -i s resposta
     [[ "$resposta" = 's' ]] && {
         fun_botOnOff
     } || {
